Code cleanup
VladAdGad/Audire pull request #279
Opened 2018-02-05 18:41 UTC by heniokalinowski

2018-02-09 20:07 UTC, VladAdGad requested changes

2018-02-09 21:33 UTC, heniokalinowski commented on Assets/Scripts/InteractableObjects/Doors/KeyLockedDoor.cs
> -        public bool IdDoorOpen() => !DoorClosed;
this class already inherits this method

2018-02-09 21:34 UTC, heniokalinowski commented on ProjectSettings/ProjectVersion.txt
> -m_EditorVersion: 2017.3.0f3
ok

2018-02-24 23:18 UTC, VladAdGad approved these changes

2018-02-24 23:19 UTC, merged